import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as React from "react";
import Container from "@material-ui/core/Container";
import { Button, Grid } from "@material-ui/core";
import { useState, useEffect } from "react";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export default function Home({ launches }) {
  const [clicked, setClicked] = useState(0);

  const [selected, setSelected] = useState(launches[0]);

  useEffect(() => {}, [clicked, selected]);

  return (
    <div>
      <Head>
        <title>Missions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Grid className={styles.container}>
        <Grid item xs={4} className={styles.missions}>
          <h1>Last Launches</h1>
          {launches.map((mission, index) => {
            return (
              <>
                {clicked !== index ? (
                  <>
                    <Button
                      onClick={() => {
                        setSelected(launches[index]);
                        setClicked(index);
                      }}
                      sx={{
                        width: 300,
                        height: 30,
                        border: "2px solid black",
                        backgroundColor: "#5d5d5d",
                        mt: "2px",
                        borderRadius: "5px",
                      }}
                    >
                      <h3 className={styles.name}>{mission.mission_name}</h3>
                    </Button>
                  </>
                ) : (
                  <Button disabled>
                    <h3 className={styles.name}>{mission.mission_name}</h3>
                  </Button>
                )}
              </>
            );
          })}
        </Grid>
        <Grid className={styles.description} item xs={8}>
          <img
            src={
              !selected.ships[0]
                ? "https://ujew.com.ua/assets/img/not_found.jpg"
                : selected.ships[0].image
            }
          />
          <h1>{selected.mission_name}</h1>
          <h2 className={styles.info}>{selected.launch_site.site_name_long}</h2>
        </Grid>
      </Grid>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      {
        launchesPast(limit: 10) {
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
          }
          ships {
            name
            home_port
            image
          }
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
